# Generated by Django 5.1.2 on 2024-10-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbracket', '0002_alter_event_date_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
