# Generated by Django 5.1.2 on 2024-10-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbracket', '0003_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='sports', to='playbracket.player'),
        ),
    ]
